name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Authenticate with gcloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}


    - name: Deploy to VM
      run: |
        gcloud compute ssh sakibal623@instance-20240404-072605 --zone=us-central1-a --command="cd /home/sakibal623/select-and-tranalate-backend && git pull"
